name: Container ops

on:
  # Triggers the workflow on push or pull request events but only for the main/master branch
  push:
    branches: [ main, master ]
jobs:
  container-ops:
    name: Build and push container image to repository
    runs-on: ubuntu-latest
    steps:
      - name: Build and push container image
        id: container_ops
        uses: orbitmi/gha-utils/actions/container-ops@VERSION
        with:
          push_image: "true or false" # default false