name: GitHub Release
on:
  repository_dispatch:
    types: [ create_github_release ]
    # inputs
    #    version: <semantic>
    #    revision: <git-sha>

jobs:
  release:
      name: Create Release >> ${{ github.event.client_payload.version || "unknow" }}
      runs-on: ubuntu-latest
      steps:
        - name: Run github-release action
          uses: htec-infra/gha-utils/actions/gh-release@VERSION
          with:
            app_version: ${{ github.event.client_payload.version }} # optional
            app_revision:  ${{ github.event.client_payload.revision }} # optional
