name: Initialize App Release

on:
  workflow_dispatch:
    inputs:
      release_type:
        type: choice
        description: Release Type
        options: [ patch, minor, major ]   

jobs:
  run:
    name: Initialization
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          # Use PAT token with workflow permissions enabled
          token: ${{ secrets.CI_PAT }}
      - name: Prepare App for Release
        id: artifact
        uses: orbitmi/gha-utils/actions/init-release@VERSION
        with:
          release_type: ${{ github.event.inputs.release_type }}
